const jugadores = [  
  // Alianza Lima
  {
    nombre: "Hernán Barcos",
    club: "Alianza Lima",
    edad: 39,
    posicion: "Delantero",
    general: 74,
    potencial: 76,
    progreso: 20,
    sprint: 72,
    regate: 70,
    pase: 68,
    tiro: 75,
    defensa: 40,
    liderazgo: 85,
    personalidad: "líder",
    motivacion: 80,
    estado_animo: "😊",
    energia: 90,
    resistencia: 65,
    lesionado: false,
    felicidad: 80,
    minutos_jugados: 210,
    titular: true,
    valor: 1500000,
    sueldo: 60000,
    contrato: 12
  },
  {
    nombre: "Pablo Sabbag",
    club: "Alianza Lima",
    edad: 30,
    posicion: "Delantero",
    general: 73,
    potencial: 75,
    progreso: 15,
    sprint: 75,
    regate: 67,
    pase: 69,
    tiro: 73,
    defensa: 38,
    liderazgo: 75,
    personalidad: "entusiasta",
    motivacion: 78,
    estado_animo: "😊",
    energia: 85,
    resistencia: 70,
    lesionado: false,
    felicidad: 75,
    minutos_jugados: 180,
    titular: true,
    valor: 1300000,
    sueldo: 55000,
    contrato: 18
  },
  // Universitario
  {
    nombre: "Álex Valera",
    club: "Universitario",
    edad: 32,
    posicion: "Delantero",
    general: 72,
    potencial: 74,
    progreso: 10,
    sprint: 74,
    regate: 66,
    pase: 67,
    tiro: 72,
    defensa: 35,
    liderazgo: 70,
    personalidad: "competitivo",
    motivacion: 82,
    estado_animo: "😊",
    energia: 88,
    resistencia: 72,
    lesionado: false,
    felicidad: 78,
    minutos_jugados: 195,
    titular: true,
    valor: 1250000,
    sueldo: 50000,
    contrato: 24
  },
  {
    nombre: "Emanuel Herrera",
    club: "Universitario",
    edad: 36,
    posicion: "Delantero",
    general: 71,
    potencial: 72,
    progreso: 5,
    sprint: 70,
    regate: 65,
    pase: 67,
    tiro: 74,
    defensa: 32,
    liderazgo: 80,
    personalidad: "tranquilo",
    motivacion: 75,
    estado_animo: "😐",
    energia: 80,
    resistencia: 68,
    lesionado: false,
    felicidad: 72,
    minutos_jugados: 150,
    titular: false,
    valor: 1200000,
    sueldo: 48000,
    contrato: 12
  },
  // Sporting Cristal
  {
    nombre: "Ignacio da Silva",
    club: "Sporting Cristal",
    edad: 29,
    posicion: "Defensa",
    general: 70,
    potencial: 72,
    progreso: 12,
    sprint: 68,
    regate: 60,
    pase: 65,
    tiro: 45,
    defensa: 78,
    liderazgo: 72,
    personalidad: "disciplinado",
    motivacion: 80,
    estado_animo: "😊",
    energia: 85,
    resistencia: 75,
    lesionado: false,
    felicidad: 76,
    minutos_jugados: 180,
    titular: true,
    valor: 1100000,
    sueldo: 45000,
    contrato: 24
  },
  {
    nombre: "Brenner Marlos",
    club: "Sporting Cristal",
    edad: 27,
    posicion: "Delantero",
    general: 75,
    potencial: 78,
    progreso: 25,
    sprint: 78,
    regate: 72,
    pase: 70,
    tiro: 76,
    defensa: 42,
    liderazgo: 68,
    personalidad: "ambicioso",
    motivacion: 85,
    estado_animo: "😄",
    energia: 92,
    resistencia: 74,
    lesionado: false,
    felicidad: 82,
    minutos_jugados: 200,
    titular: true,
    valor: 1600000,
    sueldo: 62000,
    contrato: 18
  },
  // Melgar
  {
    nombre: "Bernardo Cuesta",
    club: "Melgar",
    edad: 35,
    posicion: "Delantero",
    general: 73,
    potencial: 74,
    progreso: 8,
    sprint: 74,
    regate: 70,
    pase: 67,
    tiro: 76,
    defensa: 38,
    liderazgo: 78,
    personalidad: "experimentado",
    motivacion: 76,
    estado_animo: "😊",
    energia: 84,
    resistencia: 70,
    lesionado: false,
    felicidad: 75,
    minutos_jugados: 190,
    titular: true,
    valor: 1400000,
    sueldo: 50000,
    contrato: 12
  },
  {
    nombre: "Alec Deneumostier",
    club: "Melgar",
    edad: 31,
    posicion: "Defensa",
    general: 69,
    potencial: 71,
    progreso: 10,
    sprint: 68,
    regate: 62,
    pase: 64,
    tiro: 42,
    defensa: 76,
    liderazgo: 70,
    personalidad: "profesional",
    motivacion: 78,
    estado_animo: "😊",
    energia: 82,
    resistencia: 73,
    lesionado: false,
    felicidad: 74,
    minutos_jugados: 180,
    titular: true,
    valor: 1100000,
    sueldo: 42000,
    contrato: 24
  },
  // Cienciano
  {
    nombre: "Danilo Carando",
    club: "Cienciano",
    edad: 33,
    posicion: "Delantero",
    general: 70,
    potencial: 72,
    progreso: 5,
    sprint: 71,
    regate: 66,
    pase: 64,
    tiro: 74,
    defensa: 36,
    liderazgo: 72,
    personalidad: "determinado",
    motivacion: 76,
    estado_animo: "😐",
    energia: 80,
    resistencia: 68,
    lesionado: false,
    felicidad: 70,
    minutos_jugados: 160,
    titular: true,
    valor: 1200000,
    sueldo: 46000,
    contrato: 18
  },
  {
    nombre: "Hansell Riojas",
    club: "Cienciano",
    edad: 30,
    posicion: "Defensa",
    general: 68,
    potencial: 70,
    progreso: 8,
    sprint: 67,
    regate: 60,
    pase: 63,
    tiro: 40,
    defensa: 75,
    liderazgo: 68,
    personalidad: "constante",
    motivacion: 75,
    estado_animo: "😊",
    energia: 78,
    resistencia: 72,
    lesionado: false,
    felicidad: 72,
    minutos_jugados: 180,
    titular: true,
    valor: 1000000,
    sueldo: 40000,
    contrato: 12
  }
];

window.jugadores = jugadores;
